#################
# OpenJ9 JDK 11 #
#################
---
- name: Check for Java11 availability
  stat:
    path: /usr/java11_64
  register: java11
  tags: java11

- name: Transfer and Extract AdoptOpenJDK 11
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/11/ga/aix/ppc64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr
    remote_src: yes
  when: java11.stat.isdir is not defined
  tags: java11

- name: Find java11 directory
  find:
    file_type: directory
    paths: /usr
    patterns: 'jdk-11*'
  when: java11.stat.isdir is not defined
  register: java11_files_matched
  tags: java11

- name: Symlink to java11_64
  file:
    src: "{{ item.path }}"
    dest: /usr/java11_64
    state: link
  with_items:
    - "{{ java11_files_matched.files }}"
  when: java11.stat.isdir is not defined
  tags: java11
