---
##########
# Java 8 #
##########
- name: Test if Java 8 is already installed
  win_stat:
    path: 'C:\openjdk\jdk-8\bin'
  register: java8_installed
  tags: Java8

- name: Check if Java 8 is already downloaded
  win_stat:
    path: 'C:\temp\jdk-8.zip'
  register: java8_download
  tags: Java8

- name: Download Java 8
  win_get_url:
    url: https://api.adoptopenjdk.net/v2/binary/releases/openjdk8?openjdk_impl={{ bootjdk }}&os=windows&arch=x64&release=latest&type=jdk
    dest: 'C:\temp\jdk-8.zip'
  when: (java8_download.stat.exists == false) and (java8_installed.stat.exists == false)
  tags: Java8

- name: Install Java 8
  win_unzip:
    src: C:\temp\jdk-8.zip
    dest: C:\Program Files\Java
  when: (java8_installed.stat.exists == false)
  tags: Java8

- name: Create symlink to directory without spaces if not already there
  win_shell: for /D %a in ("C:\Program Files\Java\jdk8*") do IF NOT EXIST "C:\openjdk\jdk-8" MKLINK /D "C:\openjdk\jdk-8" "%a"
  args:
    executable: cmd.exe
    creates: 'C:\openjdk\jdk-8'
  tags: Java8

- name: Set JAVA_HOME to version 8
  win_path:
    name: JAVA_HOME
    elements: C:\openjdk\jdk-8
    scope: machine
    state: present
  when: (java8_installed.stat.exists == false)
  tags: Java8

- name: Add JAVA_HOME/bin to Path
  win_path:
    name: Path
    elements: C:\openjdk\jdk-8\bin
    scope: machine
    state: present
  when: (java8_installed.stat.exists == false)
  tags: Java8
