---
language: python
python: "2.7"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install yamllint==1.13.0
  - pip install ansible-lint==3.5.1

  # Check ansible version
  - ansible --version

script:
  - cd ansible

    # Check that the inventory is valid
  - ansible-inventory --host=build-marist-rhel74-s390x-1

    # Check YAML validity
  - yamllint -c yamllint.yml .

    # Ansible code static analysis
  - ansible-lint playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
  - ansible-lint playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
  - ansible-lint playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml
  - ansible-lint playbooks/aix.yml
  - ansible-lint playbooks/ubuntu-jck.yml

    # Check Playbook syntax.
  - ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
  - ansible-playbook playbooks/AdoptOpenJDK_Windows_Playbook/main.yml --syntax-check
  - ansible-playbook playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml --syntax-check
  - ansible-playbook playbooks/aix.yml --syntax-check
  - ansible-playbook playbooks/ubuntu-jck.yml --syntax-check
