---
################
# CodesignCert #
################

- name: Check if windows.p12 exists
  win_stat:
    path: C:\openjdk\windows.p12
  register: cert_installed
  tags:
    - ccert
    - jenkins
    - adoptopenjdk

# The vendor files are retrieved by the Get_Vendor_Files role
- name: Get windows.p12 and put in C:\openjdk Directory
  win_copy:
    src: vendor_files/windows.p12
    dest: C:\openjdk\windows.p12
  when: (not cert_installed.stat.exists)
  tags:
    - ccert
    - jenkins
    - adoptopenjdk
