---
##############################################################
# ansible install adoptopenjdk into /usr/lib/jvm/JDK_VERSION #
##############################################################

# Conditions:
# Check if target is installed
# Proceed with installing to /usr/lib/jvm

- name: Checking for /usr/lib/jvm
  stat: path=/usr/lib/jvm
  register: usr_lib_jvm_exists
  tags: adoptopenjdk_install

- name: Creating /usr/lib/jvm if not found
  file:
    path: /usr/lib/jvm
    state: directory
    owner: root
    mode: 0755
  when: usr_lib_jvm_exists.stat.exists != True
  tags: adoptopenjdk_install

- name: Check if jdk-{{ jdk_version }} is already installed in the target location
  shell: ls -ld /usr/lib/jvm/jdk-{{ jdk_version }}* >/dev/null 2>&1
  ignore_errors: yes
  register: adoptopenjdk_installed
  tags:
    - adoptopenjdk_install
    - skip_ansible_lint

- name: Install latest release if one not already installed (Linux/x64)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/{{ jdk_version }}/ga/linux/x64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk_download
  until: adoptopenjdk_download is not failed
  when:
    - adoptopenjdk_installed.rc != 0
    - ansible_architecture == "x86_64"
  tags: adoptopenjdk_install

- name: Install latest release if one not already installed (Linux/s390x)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/{{ jdk_version }}/ga/linux/s390x/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk_download
  until: adoptopenjdk_download is not failed
  when:
    - adoptopenjdk_installed.rc != 0
    - ansible_architecture == "s390x"
  tags: adoptopenjdk_install

- name: Install latest release if one not already installed (Linux/ppc64le)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/{{ jdk_version }}/ga/linux/ppc64le/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk_download
  until: adoptopenjdk_download is not failed
  when:
    - adoptopenjdk_installed.rc != 0
    - ansible_architecture == "ppc64le"
  tags: adoptopenjdk_install

- name: Install latest Hotspot release if one not already installed (Linux/aarch64)
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/{{ jdk_version }}/ga/linux/aarch64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr/lib/jvm
    remote_src: yes
  retries: 3
  delay: 5
  register: adoptopenjdk_download
  until: adoptopenjdk_download is not failed
  when:
    - adoptopenjdk_installed.rc != 0
    - ansible_architecture == "aarch64"
  tags: adoptopenjdk_install

- name: Get /usr/lib/jvm/jdk-{{ jdk_version }}* full path name
  shell: ls -ld /usr/lib/jvm/jdk-{{ jdk_version }}* 2>/dev/null | awk '{print $9}'
  register: adoptopenjdk_dir
  when: adoptopenjdk_installed.rc != 0
  tags: adoptopenjdk_install

- name: Chown /usr/lib/jvm/jdk-{{ jdk_version }}*
  file:
    path: '{{ adoptopenjdk_dir.stdout }}'
    state: directory
    owner: root
    recurse: yes
  when: adoptopenjdk_installed.rc != 0
  tags: adoptopenjdk_install
