#################
# OpenJ9 JDK 12 #
#################
---
- name: Check for Java12 availability
  stat:
    path: /usr/java12_64
  register: java12
  tags: java12

- name: Transfer and Extract AdoptOpenJDK 12
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/12/ga/aix/ppc64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr
    remote_src: yes
  when: java12.stat.isdir is not defined
  tags: java12

- name: Find java12 directory
  find:
    file_type: directory
    paths: /usr
    patterns: 'jdk-12*'
  when: java12.stat.isdir is not defined
  register: java12_files_matched
  tags: java12

- name: Symlink to java12_64
  file:
    src: "{{ item.path }}"
    dest: /usr/java12_64
    state: link
  with_items:
    - "{{ java12_files_matched.files }}"
  when: java12.stat.isdir is not defined
  tags: java12
