---
#####################
# Freemarker v2.3.8 #
#####################

- name: Test if freemarker is already installed
  win_stat:
    path: 'C:\openjdk\freemarker.jar'
  register: freemarker_installed
  tags: Freemarker

- name: Download freemarker
  win_get_url:
    url: https://repo.maven.apache.org/maven2/freemarker/freemarker/2.3.8/freemarker-2.3.8.jar
    dest: 'C:\openjdk\freemarker.jar'
    checksum: 357472da121499a66175af0a4cd5e8be84b8b4d2fdc6bcc974937937ba3003bc
    checksum_algorithm: sha256
  when: (freemarker_installed.stat.exists == false)
  tags: Freemarker
