#################
# OpenJ9 JDK 16 #
#################
---
- name: Check for Java16 availability
  stat:
    path: /usr/java16_64
  register: java16
  tags: java16

- name: Transfer and Extract AdoptOpenJDK 16
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/16/ga/aix/ppc64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr
    remote_src: yes
  when: java16.stat.isdir is not defined
  tags: java16

- name: Find java16 directory
  find:
    file_type: directory
    paths: /usr
    patterns: 'jdk-16*'
  when: java16.stat.isdir is not defined
  register: java16_files_matched
  tags: java16

- name: Symlink to java16_64
  file:
    src: "{{ item.path }}"
    dest: /usr/java16_64
    state: link
  with_items:
    - "{{ java16_files_matched.files }}"
  when: java16.stat.isdir is not defined
  tags: java16
