##############
# Boot JDK 7 #
##############
---
- name: Check for Java7 availability
  stat:
    path: /usr/j2sdk-image
  register: java7
  tags: java7

- name: Transfer and Extract Java7
  unarchive:
    src: /Vendor_Files/aix/openjdk-7u-aix.tar
    dest: /usr
    remote_src: no
  when: java7.stat.isdir is not defined
  tags: java7
