---
################
# Java_install #
################
- name: Test if Java{{ jdk_version }} is already installed
  win_stat:
    path: 'C:\openjdk\jdk-{{ jdk_version }}\bin'
  register: java_installed
  tags: Java_install

- name: Check if Java{{ jdk_version }} is already downloaded
  win_stat:
    path: 'C:\temp\jdk-{{ jdk_version }}.zip'
  register: java_download
  tags: Java_install

- name: Download Java{{ jdk_version }}
  win_get_url:
    url: https://api.adoptopenjdk.net/v2/binary/releases/openjdk{{ jdk_version }}?openjdk_impl={{ bootjdk }}&os=windows&arch=x64&release=latest&type=jdk&heap_size={{ heapsize }}
    dest: 'C:\temp\jdk-{{ jdk_version }}.zip'
  when: (java_download.stat.exists == false) and (java_installed.stat.exists == false)
  tags: Java_install

- name: Install Java{{ jdk_version }}
  win_unzip:
    src: C:\temp\jdk-{{ jdk_version }}.zip
    dest: C:\Program Files\Java
  when: (java_installed.stat.exists == false)
  tags: Java_install

- name: Create symlink to directory without spaces if not already there
  win_shell: for /D %a in ("C:\Program Files\Java\jdk-{{ jdk_version }}*") do IF NOT EXIST "C:\openjdk\jdk-{{ jdk_version }}" MKLINK /D "C:\openjdk\jdk-{{ jdk_version }}" "%a"
  args:
    executable: cmd.exe
    creates: 'C:\openjdk\jdk-{{ jdk_version }}'
  tags: Java_install
