---
#########
# gcc_7 #
#########


- name: Check if gcc 7.5 is installed on RHEL/CentOS
  shell: /usr/local/gcc/bin/gcc-7.5 --version 2>&1 > /dev/null
  ignore_errors: yes
  register: gcc7_installed
  tags: gcc-7
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "openSUSE"

# Installation on CentOS x86_64 will be handled via the scl repo in the Common CentOS playbook

- name: Download AdoptOpenJDK gcc-7.5.0 binary
  get_url:
    url: https://ci.adoptopenjdk.net/userContent/gcc/gcc750+ccache.{{ ansible_architecture }}.tar.xz
    dest: '/tmp/ansible-adoptopenjdk-gcc-7.tar.xz'
    force: no
    mode: 0644
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "openSUSE"
    - ansible_architecture != "CentOS" and ansible_architecture != "x86-64"
    - gcc7_installed.rc != 0
  tags: gcc-7

- name: Extract AdoptOpenJDK gcc-7 binary to /usr/local/gcc
  unarchive:
    src: /tmp/ansible-adoptopenjdk-gcc-7.tar.xz
    dest: /usr/local/
    copy: False
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "openSUSE"
    - ansible_architecture != "CentOS" and ansible_architecture != "x86-64"
    - gcc7_installed.rc != 0
  tags: gcc-7

- name: Remove downloaded gcc 7 binary tarball
  file:
    path: '/tmp/ansible-adoptopenjdk-gcc-7.tar.xz'
    state: absent
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "openSUSE"
    - ansible_architecture != "CentOS" and ansible_architecture != "x86-64"
    - gcc7_installed.rc != 0
  tags: gcc-7
