---
#######
# GIT #
#######

- name: Test if GIT is already installed
  win_stat:
    path: 'C:\Program Files\Git'
  register: git_installed
  tags: git

- name: Check if GIT installer is already downloaded
  win_stat:
    path: 'C:\temp\git.exe'
  register: git_download
  tags: git

- name: Download GIT installer
  win_get_url:
    url: 'https://github.com/git-for-windows/git/releases/download/v2.14.3.windows.1/Git-2.14.3-64-bit.exe'
    dest: 'C:\temp\git.exe'
    checksum: 9610e082b823beb7f0da91a98d9f73e1f3f2430c21b2c4e15517dea4f981be3f
    checksum_algorithm: sha256
  when: (not git_download.stat.exists) and (not git_installed.stat.exists)
  tags: git

- name: Create GIT properties file
  win_shell: 'New-Item -Path C:\temp -Name git_props.cfg -ItemType file -Value "[Setup]`nCRLFOption=CRLFCommitAsIs"'
  when: (not git_installed.stat.exists)
  tags: git

- name: Install GIT
  win_command: 'C:\temp\git.exe /SILENT /LOADINF="C:\temp\git_props.cfg" /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"'
  when: (not git_installed.stat.exists)
  tags: git
