################
# Jenkins user #
################
---
- name: Check for user directory existence
  stat:
    path: /home/{{ Jenkins_Username }}
  register: jenkins
  tags: jenkins_user

- debug:
    msg: "{{ Jenkins_Username }} home directory found, skipping user creation tasks"
  when: jenkins.stat.isdir is defined
  tags: jenkins_user

- name: Create jenkins user
  command: mkuser home="/home/{{ Jenkins_Username }}" shell="/bin/bash" {{ Jenkins_Username }}
  ignore_errors: yes
  when: jenkins.stat.isdir is not defined
  tags: jenkins_user

- name: Create SSH Key folder for {{ Jenkins_Username }}
  file:
    path: /home/{{ Jenkins_Username }}/.ssh
    owner: "{{ Jenkins_Username }}"
    group: staff
    mode: 0700
    state: directory
  when: jenkins.stat.isdir is not defined
  tags: jenkins_user

- name: Set authorized key for jenkins user
  authorized_key:
    user: "{{ Jenkins_Username }}"
    state: present
    key: "{{ lookup('file', '{{ Jenkins_User_SSHKey }}') }}"
  when: jenkins.stat.isdir is not defined
  tags: jenkins_user

# Use the system defaults as defined in /etc/environment
- name: Remove .profile
  file:
    state: absent
    path: /home/{{ Jenkins_Username }}/.profile
  tags: jenkins_user

- name: Set user capabilites
  command: chuser capabilities=CAP_NUMA_ATTACH,CAP_BYPASS_RAC_VMM,CAP_PROPAGATE {{ Jenkins_Username }}
  tags: jenkins_user


- name: Set group capabilites
  command: chgroup adms=root staff
  tags: jenkins_user

- name: ensure adequate limits are set in /etc/security/limits
  command: chsec -f /etc/security/limits -s {{ Jenkins_Username }} -a {{ item }}
  with_items:
    - "fsize=-1"
    - "core=-1"
    - "cpu=-1"
    - "data=262144"
    - "rss=65536"
    - "stack=65536"
    - "core_hard=-1"
    - "nofiles=-1"
    - "nofiles_hard=-1"
  changed_when: False
  tags: jenkins_user
