---
#############
# Superuser #
#############
- name: Create Superuser account - zeus
  action: user name=zeus state=present shell=/bin/bash
  when: Superuser_Account == "Enabled"
  tags: [superuser, adoptopenjdk]

- name: Create Superuser account home folder for s390x
  file:
    path: /home/zeus/
    owner: zeus
    group: zeus
    mode: 0700
    state: directory
  when:
    - ansible_architecture == "s390x"
    - Superuser_Account == "Enabled"
  tags: [superuser, adoptopenjdk]

- name: Set authorized key for Superuser account
  authorized_key:
    user: zeus
    state: present
    key: "{{ Zeus_User_SSHKey }}"
  when: Superuser_Account == "Enabled"
  tags: [superuser, superuser_authorized_key, adoptopenjdk]

- name: Grant Superuser sudo powers
  lineinfile:
    dest: "{{ Sudoers_File }}"
    state: present
    regexp: '^zeus'
    line: 'zeus ALL=(ALL) NOPASSWD: ALL'
  when: Superuser_Account == "Enabled"
  tags: [superuser, adoptopenjdk]

- name: Superuser account policy - expire date
  command: chage -E -1 zeus
  when:
    - Superuser_Account == "Enabled" and (ansible_distribution != "MacOSX")
    - ansible_distribution != "FreeBSD" and (ansible_distribution != "MacOSX")

  tags: [superuser, adoptopenjdk]

- name: Superuser account policy - max days
  command: chage -M -1 zeus
  when:
    - Superuser_Account == "Enabled" and (ansible_distribution != "MacOSX")
    - ansible_distribution != "FreeBSD" and (ansible_distribution != "MacOSX")
  tags: [superuser, adoptopenjdk]
