---
##########
# Java 9 #
##########
- name: Test if Java 9 is already installed
  win_stat:
    path: 'C:\openjdk\jdk-9\bin'
  register: java9_installed
  tags: Java9

- name: Check if Java 9 is already downloaded
  win_stat:
    path: 'C:\temp\jdk-9.zip'
  register: java9_download
  tags: Java9

- name: Download Java 9
  win_get_url:
    url: https://api.adoptopenjdk.net/v2/binary/releases/openjdk9?openjdk_impl={{ bootjdk }}&os=windows&arch=x64&release=latest&type=jdk
    dest: 'C:\temp\jdk-9.zip'
  when: (java9_download.stat.exists == false) and (java9_installed.stat.exists == false)
  tags: Java9

- name: Install Java 9
  win_unzip:
    src: C:\temp\jdk-9.zip
    dest: C:\Program Files\Java
  when: (java9_installed.stat.exists == false)
  tags: Java9

- name: Create symlink to directory without spaces if not already there
  win_shell: for /D %a in ("C:\Program Files\Java\jdk-9*") do IF NOT EXIST "C:\openjdk\jdk-9" MKLINK /D "C:\openjdk\jdk-9" "%a"
  args:
    executable: cmd.exe
    creates: 'C:\openjdk\jdk-9'
  tags: Java9
