---
##########
# RedHat #
##########

#########################################
# Configure Repos and Update the system #
#########################################
- name: Enable rhel-7-server-extras-rpms Repo for x86_64
  shell: |
    subscription-manager repos --enable=rhel-7-server-extras-rpms
    subscription-manager repos --enable rhel-7-server-optional-rpms
  ignore_errors: yes
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "x86_64"
  tags: patch_update


- name: Enable EPEL release for RHEL8
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
  ignore_errors: yes
  when:
    - ansible_architecture != "s390x"
    - ansible_distribution_major_version == "8"
  tags: patch_update

- name: YUM upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: patch_update

# TODO: We should find a better way of doing this in the future, for some reason these deps aren't in the aarch64 rhel 7 repos.
- name: Install missing Rhel7 aarch64 deps from Centos Mirror
  yum: "name={{ packages }} state=present"
  vars:
    packages:
      - http://mirror.centos.org/altarch/7/os/aarch64/Packages/libdwarf-devel-20130207-4.el7.aarch64.rpm
      - http://mirror.centos.org/altarch/7/os/aarch64/Packages/libmpc-devel-1.0.1-3.el7.aarch64.rpm
      - http://mirror.centos.org/altarch/7/os/aarch64/Packages/xorg-x11-server-common-1.20.4-7.el7.aarch64.rpm
      - http://mirror.centos.org/altarch/7/os/aarch64/Packages/xorg-x11-server-Xvfb-1.20.4-7.el7.aarch64.rpm
  when:
    - (ansible_distribution_major_version == "7" and ansible_architecture == "aarch64")
  tags: build_tools, test_tools

############################
# Build Packages and tools #
############################
- name: Call Build Packages and Tools Task
  include_tasks: build_packages_and_tools.yml

##########################
# Additional build tools #
##########################
- name: Install additional build tools if NOT RHEL 8
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_NOT_RHEL8 }}"
  when:
    - (ansible_distribution_major_version != "8")
  tags: build_tools

- name: Install additional build tools for RHEL 7
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL7 }}"
  when:
    - (ansible_distribution_major_version == "7" and ansible_architecture != "aarch64")
  tags: build_tools

- name: Install additional build tools for RHEL 7 on ppc64le
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL7_PPC64LE }}"
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "ppc64le"
  tags: build_tools

- name: Install numactl-devel excluding RHEL 7 on s390x
  package: "name=numactl-devel state=latest"
  when:
    - (ansible_distribution_major_version != "7" and ansible_architecture != "s390x")
  tags: build_tools

- name: Install additional build tools for RHEL on x86
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL_x86 }}"
  when:
    - ansible_architecture == "x86_64"
  tags: build_tools

- name: Install additional build tools for RHEL on ppc64
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL_ppc64 }}"
  when:
    - ansible_architecture == "ppc64"
  tags: build_tools

- name: Install additional build tools for RHEL on s390x
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL_s390x }}"
  when:
    - ansible_architecture == "s390x"
  tags: build_tools

- name: Install additional build tools for RHEL 8
  package: "name={{ item }} state=latest"
  with_items: "{{ Additional_Build_Tools_RHEL8 }}"
  when:
    - (ansible_distribution_major_version == "8")
  tags: build_tools

#################
# xorg Packages #
#################
- name: Install xorg-x11-server-Xorg if host is x86_64
  yum: name=xorg-x11-server-Xorg state=installed
  when: (ansible_architecture == "x86_64")
  tags: test_tools

- name: Install xorg-x11-server-common if host is s390x
  yum: name=xorg-x11-server-common state=installed
  when: (ansible_architecture == "s390x")
  tags: test_tools

################
# Install Java #
################
- name: Install Java (Not RedHat 6 on ppc64)
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_NOT_RHEL6_PPC64 }}"
  when:
    - not (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")
    - not (ansible_distribution_major_version == "8")

- name: Install Java when RedHat 6 on ppc64
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL6_PPC64 }}"
  when: (ansible_distribution_major_version == "6" and ansible_architecture == "ppc64")

- name: Install Java when RedHat 8
  package: "name={{ item }} state=latest"
  with_items: "{{ Java_RHEL8 }}"
  when: (ansible_distribution_major_version == "8")

####################
# Set default Java #
####################
- name: Set default java version - RHEL 6 x86_64
  alternatives:
    name: java
    path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
  when:
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "x86_64"
  tags: default_java

- name: Set default java version - RHEL 7 x86_64
  alternatives:
    name: java
    path: java-1.8.0-openjdk.x86_64
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "x86_64"
  tags: default_java

- name: Set default java version - RHEL 6 ppc64
  alternatives:
    name: java
    path: /usr/lib/jvm/jre-1.8.0-ibm.ppc64/bin/java
  when:
    - ansible_distribution_major_version == "6"
    - ansible_architecture == "ppc64"
  tags: default_java

- name: Set default java version - RHEL 7 ppc64
  alternatives:
    name: java
    path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.ppc64/jre/bin/java
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "ppc64"
  tags: default_java

- name: Set default java version - RHEL 7 ppc64le
  alternatives:
    name: java
    path: java-1.8.0-openjdk.ppc64le
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "ppc64le"
  tags: default_java

- name: Set default java version - RHEL 7 aarch64
  alternatives:
    name: java
    path: java-1.8.0-openjdk.aarch64
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "aarch64"
  tags: default_java

- name: Set default java version - RHEL 7 s390x
  alternatives:
    name: java
    path: java-1.8.0-openjdk.s390x
  when:
    - ansible_distribution_major_version == "7"
    - ansible_architecture == "s390x"
  tags: default_java

- name: Set default java version - RHEL 8
  alternatives:
    name: java
    path: java-1.8.0-openjdk.{{ ansible_architecture }}
  when:
    - ansible_distribution_major_version == "8"
  tags: default_java

###########
# Locales #
###########
# Skipping linting as no alternative to shell can be used (lint error 305)
- name: Get locale list
  shell: locale -a
  register: localeList
  changed_when: False
  tags:
    - locales
    - skip_ansible_lint

- name: Create Japanese locale
  locale_gen:
    name: ja_JP.UTF-8
    state: present
  when: localeList.stdout|lower is not search("ja_jp\.utf8")
  tags: locales

- name: Create Korean locale
  locale_gen:
    name: ko_KR.UTF-8
    state: present
  when: localeList.stdout|lower is not search("ko_kr\.utf8")
  tags: locales

- name: Create Chinese locale
  locale_gen:
    name: zh_CN.UTF-8
    state: present
  when: localeList.stdout|lower is not search("zh_cn\.utf8")
  tags: locales

- name: Create Taiwanese locale
  locale_gen:
    name: zh_TW.UTF-8
    state: present
  when: localeList.stdout|lower is not search("zh_tw\.utf8")
  tags: locales
