---
####################
# LLVM/Clang 64bit #
####################
# Clang 64bit is an OpenJ9 prerequisite.

- name: Test if Clang 64bit is already installed (required by OpenJ9)
  win_stat:
    path: 'C:\Program Files\LLVM\bin\clang.exe'
  register: clang_64bit_installed
  tags: clang_64bit

- name: Download Clang 64bit
  win_get_url:
    url: https://releases.llvm.org/7.0.0/LLVM-7.0.0-win64.exe
    dest: 'C:\temp\'
    force: no
    checksum: 74b197a3959b0408adf0824be01db8dddfa2f9a967f4085af3fad900ed5fdbf6
    checksum_algorithm: sha256
  when: not clang_64bit_installed.stat.exists
  tags: clang_64bit

- name: Install Clang 64bit
  win_command: 'c:\temp\LLVM-7.0.0-win64.exe /S'
  when: not clang_64bit_installed.stat.exists
  tags: clang_64bit

- name: Test if LLVM64 symlink is already created
  win_stat:
    path: 'C:\openjdk\LLVM64'
  register: llvm64_symlink
  tags: clang_64bit

- name: Create symlink to C:\openjdk\LLVM64
  raw: cmd /c mklink /D "C:\openjdk\LLVM64" "C:\Program Files\LLVM"
  when: not llvm64_symlink.stat.exists
  tags: clang_64bit

- name: Cleanup Clang 64bit installer
  win_file:
    path: 'c:\temp\LLVM-7.0.0-win64.exe'
    state: absent
  ignore_errors: yes
  tags: clang_64bit
