#####################
# superuser account #
#####################
---
- name: Setup zeus user
  command: mkuser home="/home/zeus" shell="/usr/bin/ksh" zeus
  ignore_errors: yes
  when: Superuser_Account == "Enabled"
  tags: superuser

- name: Create SSH Key folder for zeus
  file:
    path: /home/zeus/.ssh
    owner: zeus
    group: staff
    mode: 0700
    state: directory
  when: Superuser_Account == "Enabled"
  tags: superuser

- name: Add key
  authorized_key:
    user: zeus
    state: present
    key: "{{ lookup('file', '{{ Zeus_User_SSHKey }}') }}"
  when: Superuser_Account == "Enabled"
  tags: superuser

- name: Grant zeus sudo powers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^zeus'
    line: 'zeus ALL=(ALL) NOPASSWD: ALL'
  when: Superuser_Account == "Enabled"
  tags: superuser
