#################
# OpenJ9 JDK 10 #
#################
---
- name: Check for Java10 availability
  stat:
    path: /usr/java10_64
  register: java10
  tags: java10

- name: Transfer and Extract AdoptOpenJDK 10
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/10/ga/aix/ppc64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr
    remote_src: yes
  when: java10.stat.isdir is not defined
  tags: java10

- name: Find java10 directory
  find:
    file_type: directory
    paths: /usr
    patterns: 'jdk-10*'
  when: java10.stat.isdir is not defined
  register: java10_files_matched
  tags: java10

- name: Symlink to java10_64
  file:
    src: "{{ item.path }}"
    dest: /usr/java10_64
    state: link
  with_items:
    - "{{ java10_files_matched.files }}"
  when: java10.stat.isdir is not defined
  tags: java10
