---
########
# nasm #
########
- name: Check if nasm is installed
  win_stat:
    path: C:\openjdk\nasm-2.13.03
  register: nasm_installed
  tags: nasm

- name: Download nasm
  win_get_url:
    url: https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/win64/nasm-2.13.03-win64.zip
    dest: C:\temp\nasm-2.13.03.zip
    checksum: b3a1f896b53d07854884c2e0d6be7defba7ebd09b864bbb9e6d69ada1c3e989f
    checksum_algorithm: sha256
  when: (not nasm_installed.stat.exists)
  tags: nasm

- name: Unzip nasm
  win_unzip:
    src: C:\temp\nasm-2.13.03.zip
    dest: C:\openjdk
    delete_archive: yes
  when: (not nasm_installed.stat.exists)
  tags: nasm
