---
###########
# Firefox #
###########

- name: Test if Firefox is already installed
  win_stat:
    path: 'C:\Program Files\Mozilla Firefox\firefox.exe'
  register: firefox_installed
  tags: Firefox

- name: Check if Firefox is already downloaded
  win_stat:
    path: 'C:\temp\firefox.exe'
  register: firefox_download
  tags: Firefox

- name: Download Firefox
  win_get_url:
    url: https://ftp.mozilla.org/pub/firefox/releases/54.0/win64/en-GB/Firefox%20Setup%2054.0.exe
    dest: 'C:\temp\firefox.exe'
    checksum: 9a1fbbb7eb68347decafbf048fc9728777fc213fefc5224119625b1f58a626fc
    checksum_algorithm: sha256
  when: (not firefox_download.stat.exists) and (not firefox_installed.stat.exists)
  tags: Firefox

- name: Install Firefox
  raw: C:\temp\firefox.exe -ms
  when: (not firefox_installed.stat.exists)
  tags: Firefox
