---
#########
# Rust #
#########

- name: Test if Rust is already installed
  win_stat:
    path: 'C:\Program Files\Rust stable MSVC 1.33\bin\rustc.exe'
  register: rust_installed
  tags: Rust

- name: Download Rust installer
  win_get_url:
    url: https://static.rust-lang.org/dist/rust-1.33.0-x86_64-pc-windows-msvc.msi
    dest: 'C:\temp\rust.msi'
    force: no
  when: (rust_installed.stat.exists == false)
  tags: Rust

- name: Install Rust
  raw: msiexec /i C:\temp\rust.msi INSTALLDIR="c:\rust" /quiet
  ignore_errors: yes
  when: (rust_installed.stat.exists == false)
  tags: Rust

- name: Cleanup Rust
  win_file:
    path: C:\temp\rust.msi
    state: absent
  ignore_errors: yes
  tags: Rust
