---
###########
# Java 12 #
###########
- name: Test if Java12 is already installed
  win_stat:
    path: 'C:\openjdk\jdk-12\bin'
  register: java12_installed
  tags: Java12

- name: Check if Java12 is already downloaded
  win_stat:
    path: 'C:\temp\jdk-12.zip'
  register: java12_download
  tags: Java12

- name: Download Java12
  win_get_url:
    url: https://api.adoptopenjdk.net/v2/binary/releases/openjdk12?openjdk_impl={{ bootjdk }}&os=windows&arch=x64&release=latest&type=jdk
    dest: 'C:\temp\jdk-12.zip'
  when: (java12_download.stat.exists == false) and (java12_installed.stat.exists == false)
  tags: Java12

- name: Install Java12
  win_unzip:
    src: C:\temp\jdk-12.zip
    dest: C:\Program Files\Java
  when: (java12_installed.stat.exists == false)
  tags: Java12

- name: Create symlink to directory without spaces if not already there
  win_shell: for /D %a in ("C:\Program Files\Java\jdk-12*") do IF NOT EXIST "C:\openjdk\jdk-12" MKLINK /D "C:\openjdk\jdk-12" "%a"
  args:
    executable: cmd.exe
    creates: 'C:\openjdk\jdk-12'
  tags: Java12
