---
##########
# macOS #
##########

# Command Build Tool Packages

Build_Tool_Packages:
  - autoconf
  - ccache
  - cmake # OpenJ9
  - coreutils
  - gnu-sed
  - gnu-tar
  - nasm # openj9 jdk13+
  - wget

Build_Tool_Packages_NOT_arm64:
  - bash # OpenJ9 needs bash v4 or later

Build_Tool_Casks:
  - adoptopenjdk10
  - packages

Test_Tool_Packages:
  - mercurial

Test_Tool_Packages_NOT_arm64:
  - pulseaudio

Test_Tool_Casks:
  - xquartz
