##############
# Boot JDK 9 #
##############
---
- name: Check for Java9 availability
  stat:
    path: /usr/java9_64
  register: java9
  tags: java9

- name: Transfer and Extract AdoptOpenJDK 9
  unarchive:
    src: https://api.adoptopenjdk.net/v3/binary/latest/9/ga/aix/ppc64/jdk/{{ bootjdk }}/normal/adoptopenjdk?project=jdk
    dest: /usr
    remote_src: yes
  when: java9.stat.isdir is not defined
  tags: java9

- name: Find java9 directory
  find:
    file_type: directory
    paths: /usr
    patterns: 'jdk-9*'
  when: java9.stat.isdir is not defined
  register: java9_files_matched
  tags: java9

- name: Symlink to java9_64
  file:
    src: "{{ item.path }}"
    dest: /usr/java9_64
    state: link
  with_items:
    - "{{ java9_files_matched.files }}"
  when: java9.stat.isdir is not defined
  tags: java9
