name: Build

on:
  pull_request:
    paths:
    - ansible/**
    branches:         
    - master
  push:
    paths:
    - ansible/**
    branches:         
    - master

env:
  CONTAINER_IMAGE: adoptopenjdk/centos6_image
  SLAVE_IMAGE: adoptopenjdk/jenkins_slave

jobs:
  build-and-push:
    name: Building and pushing image to Dockerhub
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Docker Build & Push Centos6 Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.CentOS6
        repository: adoptopenjdk/centos6_build_image
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}

    - name: Docker Build & Push Jenkins Slave Image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./ansible/Dockerfile.JenkinsSlave
        repository: adoptopenjdk/jenkins_slave
        tags: latest
        push: ${{ github.ref == 'refs/heads/master' }}